return {
  kinds = {
    Array = "󰅪",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "󰡱",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "󰠲",
    Namespace = "",
    Null = "󰟢",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  debug = {
    breakpoints = "",
    stacks = "",
    scopes = "󰮄",
    watches = "",
  },
  separator = {
    bold_right_arrow = "",
    right_arrow = ">",
    slash = "/",
    limit = "...",
    space = " ",
    bold_left_line = "▎",
  },
  file = {
    self = "󰑷",
    state_mod = "",
    state_readonly = "",
  },
  git = {
    branch = "",
  },
  diff = {
    added = "+",
    modified = "~",
    removed = "-",
  },
  diagnostics = {
    error = "",
    warn = "",
    info = "",
    hint = "󰫢",
  },
}
